TEXT_GENERATOR_TITLE = 'Shakspear Text Generator'
TEXT_GENERATOR_DESCRIPTION = 'TEXT_GENERATOR_DESCRIPTION'

CLASSIFY_TWITTER_TITLE = 'CLASSIFY_TWITTER_TITLE'
CLASSIFY_TWITTER_DESCRIPTION = 'CLASSIFY_TWITTER_DESCRIPTION'

HOME_PAGE_TITLE = 'HOME_PAGE_TITLE'
HOME_PAGE_TEXT = 'HOME_PAGE_TEXT'