TEXT_GENERATOR_TITLE = 'Shakspear Text Generator'
TEXT_GENERATOR_DESCRIPTION = 'TEXT_GENERATOR_DESCRIPTION'

CLASSIFY_TWITTER_TITLE = 'Are those Lakers or Clippers tweets?'
CLASSIFY_TWITTER_DESCRIPTION = 'CLASSIFY_TWITTER_DESCRIPTION'

HOME_PAGE_TITLE = 'HOME_PAGE_TITLE'
HOME_PAGE_TEXT = 'HOME_PAGE_TEXT'

Lackers = 1
Clippers = 0

#TEXT GENERATOR RELATED
MAX_TEXT_GEN_OUTPUT = 1000
MAX_SEED_LEN = 30

MAX_SEED_LEN_NGRAM = 4
MAX_SEED_LEN_CHAR = 15
MAX_OUTPUT_LEN = 1000
GENERATION_METHOD= {'characters':0,'n-gram':1,'RNN':2}
MAX_PREFIX_LEN = 15
CLASSIFICATION_MAPPING = {'Lakers':0,'Clippers':1}